### ISSUE TITLE
what is the different between miniFE and HPCG?

### ISSUE THREAD

**Issue by lwh1990** [Mantevo/miniFE#12]
Hi, what is the different between miniFE and HPCG?

**Comment by nmhamster** [comment]
@lwh1990 - MiniFE does not have a preconditioner. The fundamental kernels are similar (identical in the CG solve). MiniFE was written earlier as a test tool/mini-app for studying simple linear algebra routines. Does that help?

**Comment by maherou** [comment]
A few more details:
- miniFE constructs a linear system using a simple finite element method, constructing the global stiffness matrix from local element contributions.
- HPCG constructs a linear system from a simplified 4th order compact finite difference scheme.
- Both result in a 27-point stencil operator.
- As Si said, miniFE uses unpreconditioned CG.
- HPCG uses a truncated multigrid preconditioned with symmetric Gauss-Seidel smoothers along with CG.

Generally, getting good performance from HPCG is more challenging than miniFE, because of the Gauss-Seidel smoother.  A good implementation of HPCG on modern, highly-concurrent architectures requires use of multi-colored Gauss-Seidel and getting good SIMT or SIMD execution of the related sparse kernels.
