### ISSUE TITLE
Could you provide some tips on how to run this project in the CLion IDE?

### ISSUE THREAD

**Issue by eirhardt** [Mantevo/miniFE#8]
Could you provide some tips on how to run this project in the CLion IDE?

**Comment by maherou** [comment]
@eirhardt, I am only slightly familiar with CLion, but it is my understanding that CLion relies on CMake to define and manage its project.  We have not developed CMake support for MiniFE.  If you have some familiarity with CMake, I am guessing it would be fairly straightforward for you you create a simple CMakeLists.txt file for MiniFE.  CLion has some tutorial material on how to do so.  

Since we often run MiniFE and other Mantevo mini apps on testbed platforms that don't have the full complement of Linux/Unix build tools, we have avoided using CMake, since requiring it could create an unnecessary impediment in these environments.

This response is probably not as helpful as you would like, but it is the best we can do for now.

**Comment by eirhardt** [comment]
No worries. Thanks for the info.
